title: rnrn213
description: rnrn213 github page
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://rnrn213.github.io

aux_links:
  Template Repository: https://github.com/rnrn213/rnrn213.github.io
